# Generated by Django 3.1.5 on 2021-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitnagar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
