# Generated by Django 3.1.5 on 2021-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amitnagar', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('discription', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='upload/products')),
            ],
        ),
    ]
