# Generated by Django 3.1.5 on 2021-01-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amitnagar', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
