# Generated by Django 3.1.5 on 2021-01-26 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amitnagar', '0009_auto_20210124_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amitnagar.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amitnagar.product')),
            ],
        ),
    ]
